[book]
title = "Typst Extra Docs"
authors = []
description = "An unofficial collection of extra official documentations for Typst."
language = "en"

[output.html.search.chapter]
# Disables search indexing for licenses
"license" = { enable = false }

[output.html.playground]
# hayagriva/index.md contains rust codes, but the Rust Playground does not support the hayagriva crate
runnable = false

[preprocessor.clean-pulldown-cmark]
command = "uv run scripts/clean_pulldown_cmark.py"
# After all other preprocessors.
after = ["typst-highlight", "typst-extra-docs"]

[preprocessor.typst-highlight]
# Install it by running
#   cargo install --git https://github.com/sitandr/mdbook-typst-highlight --branch main
# It's d7c197c6, the unreleased version.

# Inline highlighting must be disabled due to technical limitations.
# This preprocessor highlights inline codes by converting them to HTML fragments in markdown.
# However, special characters (e.g., `_*|`) in them are not properly escaped, resulting in poor rendering.
disable_inline = true

[preprocessor.typst-extra-docs]
command = "cargo run --release --manifest-path ./typst-extra-docs/Cargo.toml"

[preprocessor.typst-extra-docs.download]
# Format: `git log -1 --format='%h %ad' --date=iso-strict`
# `%ad` can also be obtained from GitHub API: `gh api /repos/typst/REPO/commits/COMMIT --jq .commit.author.date`
typst = "a51e02804 2026-08-07T15:01:39+02:00"
codex = "930ec5c 2026-07-09T13:15:58Z"
hayagriva = "5a71313 2026-07-15T10:21:09+02:00"
packages = "8aa59a2 2026-08-11T08:46:57Z"
